const materias = [
  { nombre: "Cálculo diferencial", creditos: 3, semestre: 1 },
  { nombre: "Álgebra lineal", creditos: 3, semestre: 1 },
  { nombre: "Introducción a la ingeniería", creditos: 2, semestre: 1 },
  { nombre: "Dibujo de ingeniería", creditos: 2, semestre: 1 },
  { nombre: "Comunicación oral y escrita", creditos: 2, semestre: 1 },
  { nombre: "Cátedra de Henri Didon", creditos: 0, semestre: 1 },
  { nombre: "Inglés 1", creditos: 2, semestre: 1 },

  { nombre: "Cálculo integral", creditos: 3, semestre: 2, prereq: ["Cálculo diferencial"] },
  { nombre: "Física mecánica", creditos: 3, semestre: 2, prereq: ["Cálculo diferencial"] },
  { nombre: "Química general", creditos: 3, semestre: 2 },
  { nombre: "Probabilidad y estadística", creditos: 2, semestre: 2 },
  { nombre: "Dibujo de máquinas", creditos: 2, semestre: 2, prereq: ["Dibujo de ingeniería"] },
  { nombre: "Lógica de programación", creditos: 3, semestre: 2 },
  { nombre: "Inglés 2", creditos: 2, semestre: 2, prereq: ["Inglés 1"] },

  { nombre: "Cálculo vectorial", creditos: 3, semestre: 3, prereq: ["Cálculo integral"] },
  { nombre: "Electricidad y magnetismo", creditos: 3, semestre: 3, prereq: ["Física mecánica"] },
  { nombre: "Ciencia de materiales", creditos: 2, semestre: 3 },
  { nombre: "Estática", creditos: 3, semestre: 3, prereq: ["Física mecánica"] },
  { nombre: "Programación orientada a objetos", creditos: 2, semestre: 3, prereq: ["Lógica de programación"] },
  { nombre: "Antropología", creditos: 2, semestre: 3 },
  { nombre: "Inglés 3", creditos: 2, semestre: 3, prereq: ["Inglés 2"] },

  { nombre: "Ecuaciones diferenciales", creditos: 3, semestre: 4, prereq: ["Cálculo vectorial"] },
  { nombre: "Termofluidos", creditos: 3, semestre: 4, prereq: ["Física mecánica"] },
  { nombre: "Dinámica", creditos: 3, semestre: 4, prereq: ["Estática"] },
  { nombre: "Circuitos eléctricos", creditos: 3, semestre: 4, prereq: ["Electricidad y magnetismo"] },
  { nombre: "Lab de circuitos", creditos: 1, semestre: 4, prereq: ["Circuitos eléctricos"] },
  { nombre: "Epistemología", creditos: 2, semestre: 4 },
  { nombre: "Inglés 4", creditos: 2, semestre: 4, prereq: ["Inglés 3"] },

  { nombre: "Análisis numérico", creditos: 2, semestre: 5, prereq: ["Ecuaciones diferenciales"] },
  { nombre: "Señales", creditos: 3, semestre: 5 },
  { nombre: "Resistencia de materiales", creditos: 3, semestre: 5, prereq: ["Estática"] },
  { nombre: "Máquinas eléctricas y laboratorio", creditos: 3, semestre: 5, prereq: ["Circuitos eléctricos"] },
  { nombre: "Electrónica analógica", creditos: 3, semestre: 5, prereq: ["Circuitos eléctricos"] },
  { nombre: "Lab de electrónica", creditos: 1, semestre: 5, prereq: ["Electrónica analógica"] },
  { nombre: "Cátedra opcional 1", creditos: 1, semestre: 5 },
  { nombre: "Inglés 5", creditos: 2, semestre: 5, prereq: ["Inglés 4"] },

  { nombre: "Sistemas oleoneumáticos y laboratorio", creditos: 3, semestre: 6 },
  { nombre: "Diseño de elementos de máquinas", creditos: 3, semestre: 6, prereq: ["Resistencia de materiales"] },
  { nombre: "Automatismos", creditos: 2, semestre: 6 },
  { nombre: "Instrumentación industrial y lab", creditos: 2, semestre: 6 },
  { nombre: "Electrónica digital", creditos: 3, semestre: 6 },
  { nombre: "Lab electrónica digital", creditos: 1, semestre: 6, prereq: ["Electrónica digital"] },
  { nombre: "Cátedra opcional complementaria 1", creditos: 1, semestre: 6 },
  { nombre: "Inglés 6", creditos: 2, semestre: 6, prereq: ["Inglés 5"] },

  { nombre: "Automatización industrial y lab", creditos: 3, semestre: 7, prereq: ["Automatismos"] },
  { nombre: "Análisis de sistemas dinámicos", creditos: 3, semestre: 7, prereq: ["Ecuaciones diferenciales"] },
  { nombre: "Procesos de manufactura y lab", creditos: 2, semestre: 7 },
  { nombre: "Electrónica de potencia y lab", creditos: 3, semestre: 7, prereq: ["Electrónica analógica"] },
  { nombre: "Sistemas embebidos", creditos: 2, semestre: 7 },
  { nombre: "Cátedra opcional complementaria 2", creditos: 1, semestre: 7 },
  { nombre: "Cátedra opcional 2", creditos: 1, semestre: 7 },
  { nombre: "Economía para ingenieros", creditos: 2, semestre: 7 },

  { nombre: "Electiva profesional 1", creditos: 2, semestre: 8 },
  { nombre: "Electiva profesional 2", creditos: 2, semestre: 8 },
  { nombre: "Comunicaciones industriales y lab", creditos: 3, semestre: 8 },
  { nombre: "Sistemas de control 1 y lab", creditos: 3, semestre: 8, prereq: ["Análisis de sistemas dinámicos"] },
  { nombre: "Inteligencia artificial", creditos: 2, semestre: 8 },
  { nombre: "Cátedra opcional complementaria 3", creditos: 1, semestre: 8 },
  { nombre: "Cultura teológica", creditos: 2, semestre: 8 },
  { nombre: "Gestión de proyectos", creditos: 2, semestre: 8 },

  { nombre: "Electiva profesional 3", creditos: 2, semestre: 9 },
  { nombre: "Electiva profesional 4", creditos: 2, semestre: 9 },
  { nombre: "Robótica y lab", creditos: 3, semestre: 9, prereq: ["Sistemas embebidos"] },
  { nombre: "Sistemas de control 2 y lab", creditos: 3, semestre: 9, prereq: ["Sistemas de control 1 y lab"] },
  { nombre: "Diseño mecatrónico", creditos: 3, semestre: 9 },
  { nombre: "Filosofía política", creditos: 2, semestre: 9 },
  { nombre: "Legislación", creditos: 2, semestre: 9 },

  { nombre: "Electiva profesional 5", creditos: 2, semestre: 10 },
  { nombre: "Electiva profesional 6", creditos: 2, semestre: 10 },
  { nombre: "Proyecto de grado o pasantía", creditos: 4, semestre: 10 },
  { nombre: "Ética", creditos: 2, semestre: 10 },
  { nombre: "Cátedra opcional 3", creditos: 1, semestre: 10 }
];
